name: stitch-keeper
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ashleylclark/stitch-keeper:0.1.0
    environment:
      PORT: 3001
      SQLITE_PATH: /app/data/stitch-keeper.db
    ports:
      - '8080:3001'
    volumes:
      - stitch-keeper-data:/app/data

volumes:
  stitch-keeper-data:
