export const stashItems = [
  {
    id: 's1',
    category: 'yarn',
    name: 'Bulky acrylic yarn - Charcoal',
    brand: 'Lion Brand',
    color: 'Charcoal',
    material: 'Acrylic',
    weight: 'bulky',
    quantity: 3,
    unit: 'skeins',
    status: 'in-stock',
  },
  {
    id: 's2',
    category: 'hook',
    name: 'Aluminum hook',
    brand: 'Clover',
    quantity: 1,
    size: '8 mm',
    status: 'in-stock',
  },
  {
    id: 's3',
    category: 'yarn',
    name: 'DK weight yarn set - Assorted colors',
    brand: 'Stylecraft',
    color: 'Assorted',
    material: 'Acrylic',
    weight: 'dk',
    quantity: 10,
    unit: 'skeins',
    status: 'in-stock',
  },
  {
    id: 's4',
    category: 'hook',
    name: '4 mm hook',
    brand: 'Clover',
    quantity: 1,
    size: '4 mm',
    status: 'in-stock',
  },
  {
    id: 's5',
    category: 'hook',
    name: '5 mm hook',
    brand: 'Clover',
    quantity: 1,
    size: '5 mm',
    status: 'in-stock',
  },
  {
    id: 's6',
    category: 'yarn',
    name: 'Sport weight cotton yarn - Natural',
    brand: 'Paintbox',
    color: 'Natural',
    material: 'Cotton',
    weight: 'sport',
    quantity: 5,
    unit: 'skeins',
    status: 'in-stock',
  },
  {
    id: 's7',
    category: 'yarn',
    name: 'Worsted wool yarn - Cream',
    brand: 'Knit Picks',
    color: 'Cream',
    material: 'Wool blend',
    weight: 'worsted',
    quantity: 0,
    unit: 'skeins',
    status: 'out-of-stock',
    notes: 'Used up for the cardigan body.',
  },
  {
    id: 's8',
    category: 'hook',
    name: '6 mm hook',
    brand: 'Tulip',
    quantity: 1,
    size: '6 mm',
    status: 'in-stock',
  },
  {
    id: 's9',
    category: 'yarn',
    name: 'Fingering weight yarn - Baby pink',
    brand: 'Cascade',
    color: 'Baby Pink',
    material: 'Merino',
    weight: 'fingering',
    quantity: 2,
    unit: 'skeins',
    status: 'low-stock',
  },
  {
    id: 's10',
    category: 'yarn',
    name: 'Fingering weight yarn - Baby blue',
    brand: 'Cascade',
    color: 'Baby Blue',
    material: 'Merino',
    weight: 'fingering',
    quantity: 2,
    unit: 'skeins',
    status: 'not-replacing',
    notes: 'Left over from a finished baby blanket set.',
  },
  {
    id: 's11',
    category: 'needle',
    name: 'Bent-tip tapestry needles',
    brand: 'Susan Bates',
    quantity: 2,
    unit: 'needles',
    status: 'in-stock',
  },
  {
    id: 's12',
    category: 'eyes',
    name: '12 mm safety eyes',
    quantity: 14,
    unit: 'pairs',
    size: '12 mm',
    status: 'low-stock',
  },
  {
    id: 's13',
    category: 'stuffing',
    name: 'Polyfill bag',
    quantity: 1,
    unit: 'bag',
    status: 'in-stock',
  },
  {
    id: 's14',
    category: 'other',
    name: 'Stitch markers',
    quantity: 24,
    unit: 'markers',
    status: 'in-stock',
  },
]

export const patterns = [
  {
    id: '101',
    name: 'Chunky Cowl',
    addedAt: '2026-03-02',
    isPlanned: 0,
    category: 'accessory',
    difficulty: 'beginner',
    notes: 'Soft, quick project for winter gifting.',
    instructions: 'Chain 60. Join with slip stitch to form a ring, being careful not to twist the chain. Round 1: Chain 2 (counts as first dc), dc in each chain around. Join with slst to top of beginning chain-2. Round 2: Chain 2, double crochet in each stitch around. Join with slst to top of beginning chain-2. Repeat Round 2 until cowl measures approximately 12 inches from the join, or desired length. Fasten off and weave in ends.',
    requirements: [
      { id: '101-yarn', category: 'yarn', name: 'Bulky acrylic yarn', weight: 'bulky', quantityNeeded: 2, unit: 'skeins' },
      { id: '101-hook', category: 'hook', name: '8 mm hook', size: '8 mm' },
    ],
  },
  {
    id: '102',
    name: 'Granny Square Blanket',
    addedAt: '2026-02-20',
    isPlanned: 0,
    category: 'blanket',
    difficulty: 'intermediate',
    notes: 'Great stash-buster with lots of color flexibility.',
    instructions: 'Chain 60. Join with slip stitch to form a ring, being careful not to twist the chain. Round 1: Chain 2 (counts as first dc), double crochet in each chain around. Join with slip stitch to top of beginning chain-2. Round 2: Chain 2, double crochet in each stitch around. Join with slip stitch to top of beginning chain-2. Repeat Round 2 until blanket measures approximately 36 inches from the join, or desired length. Fasten off and weave in ends.',
    requirements: [
      { id: '102-yarn', category: 'yarn', name: 'DK weight yarn set', weight: 'dk', quantityNeeded: 8, unit: 'skeins' },
      { id: '102-hook', category: 'hook', name: '4 mm hook', size: '4 mm' },
    ],
  },
  {
    id: '103',
    name: 'Market Tote',
    addedAt: '2026-03-08',
    isPlanned: 1,
    category: 'bag',
    difficulty: 'beginner',
    notes: 'Simple everyday tote with sturdy handles.',
    instructions: 'Chain 40. Join with slip stitch to form a ring, being careful not to twist the chain. Round 1: Chain 2 (counts as first dc), double crochet in each chain around. Join with slip stitch to top of beginning chain-2. Round 2: Chain 2, double crochet in each stitch around. Join with slip stitch to top of beginning chain-2. Repeat Round 2 until tote measures approximately 12 inches from the join, or desired length. Fasten off and weave in ends.',
    requirements: [
      { id: '103-yarn', category: 'yarn', name: 'Cotton yarn', weight: 'worsted', quantityNeeded: 3, unit: 'skeins' },
      { id: '103-hook', category: 'hook', name: '5 mm hook', size: '5 mm' },
    ],
  },
  {
    id: '104',
    name: 'Patchwork Cardigan',
    addedAt: '2026-03-10',
    isPlanned: 0,
    category: 'garment',
    difficulty: 'advanced',
    notes: 'Color-blocked cardigan made from joined crochet panels.',
    instructions: 'Chain 60. Join with slip stitch to form a ring, being careful not to twist the chain. Round 1: Chain 2 (counts as first dc), double crochet in each chain around. Join with slip stitch to top of beginning chain-2. Round 2: Chain 2, double crochet in each stitch around. Join with slip stitch to top of beginning chain-2. Repeat Round 2 until cardigan measures approximately 24 inches from the join, or desired length. Fasten off and weave in ends.',
    requirements: [
      { id: '104-yarn', category: 'yarn', name: 'Worsted wool blend', weight: 'worsted', quantityNeeded: 10, unit: 'skeins' },
      { id: '104-hook', category: 'hook', name: '6 mm hook', size: '6 mm' },
    ],
  },
  {
    id: '105',
    name: 'Weekend Bucket Hat',
    addedAt: '2026-03-11',
    isPlanned: 0,
    category: 'accessory',
    difficulty: 'beginner',
    notes: 'Quick warm-weather make with a structured brim.',
    instructions: 'Chain 60. Join with slip stitch to form a ring, being careful not to twist the chain. Round 1: Chain 2 (counts as first dc), double crochet in each chain around. Join with slip stitch to top of beginning chain-2. Round 2: Chain 2, double crochet in each stitch around. Join with slip stitch to top of beginning chain-2. Repeat Round 2 until hat measures approximately 8 inches from the join, or desired length. Fasten off and weave in ends.',
    requirements: [
      { id: '105-yarn', category: 'yarn', name: 'Cotton yarn', weight: 'worsted', quantityNeeded: 2, unit: 'skeins' },
      { id: '105-hook', category: 'hook', name: '5 mm hook', size: '5 mm' },
    ],
  },
  {
    id: '106',
    name: 'Flower Coaster Set',
    addedAt: '2026-03-06',
    isPlanned: 0,
    category: 'home',
    difficulty: 'beginner',
    notes: 'Small scrap project that works up fast.',
    instructions: 'Chain 20. Join with slip stitch to form a ring, being careful not to twist the chain. Round 1: Chain 2 (counts as first dc), double crochet in each chain around. Join with slip stitch to top of beginning chain-2. Round 2: Chain 2, double crochet in each stitch around. Join with slip stitch to top of beginning chain-2. Repeat Round 2 until coaster measures approximately 4 inches from the join, or desired size. Fasten off and weave in ends.',
    requirements: [
      { id: '106-yarn', category: 'yarn', name: 'Cotton scraps', weight: 'dk', quantityNeeded: 1, unit: 'set' },
      { id: '106-hook', category: 'hook', name: '4 mm hook', size: '4 mm' },
    ],
  },
]

export const projects = [
  { id: 'chunky-cowl', name: 'Chunky Cowl', patternId: '101', startDate: '2024-05-01', stashItemIds: ['s1', 's2'], status: 'in-progress', notes: 'On round 12' },
  { id: 'granny-square-blanket', name: 'Granny Square Blanket', patternId: '102', startDate: '2024-04-15', stashItemIds: ['s3', 's4', 's5'], status: 'in-progress', notes: '24 of 80 squares joined' },
  { id: 'market-tote', name: 'Market Tote', patternId: '103', stashItemIds: ['s6'], status: 'planned', notes: 'For a birthday gift' },
  { id: 'patchwork-cardigan', name: 'Patchwork Cardigan', patternId: '104', stashItemIds: ['s7', 's8'], status: 'need-supplies', notes: 'Need two more skeins of cream yarn' },
  { id: 'striped-baby-blanket', name: 'Striped Baby Blanket', patternId: '107', startDate: '2025-11-18', endDate: '2025-12-10', stashItemIds: ['s9', 's10'], status: 'completed', notes: 'Finished and gifted last winter.' },
]
